[project]
name = 'markets'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.market]
path = 'contracts/market.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
